---
"on":
  release:
    types: [published]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Github Releases To Discord
        uses: SethCohen/github-releases-to-discord@v1.13.1
        with:
          webhook_url: ${{ secrets.DISCORD_ANNOUNCEMENT_WEBHOOK }}
          color: "2105893"
          username: "GitHub"
          avatar_url: "https://cdn.discordapp.com/avatars/1161539752152010772/bd191bb555f01bd4f328efe9fb4cda2f.png"
          footer_title: "Changelog"
          footer_icon_url: "https://cdn.discordapp.com/avatars/1161539752152010772/bd191bb555f01bd4f328efe9fb4cda2f.png"
          footer_timestamp: true