---
name: Build & Publish container
"on":
  push:
    branches: [main]

jobs:
  publish:
    uses: actionshub/reusable-workflows/.github/workflows/publish.yaml@8acb1daa3c8ccd4c6564809e30c6ec568b3cfbd5
