---
name: Build & Publish container
"on":
  push:
    branches: [main]

jobs:
  publish:
    uses: actionshub/reusable-workflows/.github/workflows/publish.yaml@99738725f4b9330dee12acfa730290a037031600
