---
name: Build & Publish container
"on":
  push:
    branches: [main]

jobs:
  pull_request:
    uses: actionshub/reusable-workflows/.github/workflows/publish.yaml@f72b4965de569759f8927de3c639b063f8cde0cd
